apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeout-random-deployment
  namespace: resilience
spec:
  selector:
    matchLabels:
      app: timeout-random
  replicas: 3
  template:
    metadata:
      labels:
        app: timeout-random
    spec:
      containers:
      - name: timeout-random
        image: wjsc/timeout-random:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"