apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: resilience-ingress
  namespace: resilience
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: client-service
          servicePort: 4000
