apiVersion: apps/v1
kind: Deployment
metadata:
  name: stop-deployment
  namespace: resilience
spec:
  selector:
    matchLabels:
      app: stop
  replicas: 1
  template:
    metadata:
      labels:
        app: stop
    spec:
      containers:
      - name: stop
        image: wjsc/stop:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"