apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeout-deployment
spec:
  selector:
    matchLabels:
      app: timeout
  replicas: 3
  template:
    metadata:
      labels:
        app: timeout
    spec:
      containers:
      - name: timeout
        image: wjsc/timeout:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"