apiVersion: linkerd.io/v1alpha1
kind: ServiceProfile
metadata:
  name: bmxxnts66d.execute-api.us-east-1.amazonaws.com
  namespace: resilience
spec:
  routes:
  - name: '/default/fail-random-remote'
    condition:
      pathRegex: '/default/fail-random-remote'
      method: GET
    isRetryable: true
    timeout: 2000ms
  retryBudget:
    retryRatio: 0.2
    minRetriesPerSecond: 10
    ttl: 10s
