apiVersion: apps/v1
kind: Deployment
metadata:
  name: fail-deployment
  namespace: resilience
spec:
  selector:
    matchLabels:
      app: fail
  replicas: 3
  template:
    metadata:
      labels:
        app: fail
    spec:
      containers:
      - name: fail
        image: wjsc/fail:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"