apiVersion: apps/v1
kind: Deployment
metadata:
  name: crash-random-deployment
spec:
  selector:
    matchLabels:
      app: crash-random
  replicas: 3
  template:
    metadata:
      labels:
        app: crash-random
    spec:
      containers:
      - name: crash-random
        image: wjsc/crash-random:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"