apiVersion: apps/v1
kind: Deployment
metadata:
  name: crash-deployment
  namespace: resilience
spec:
  selector:
    matchLabels:
      app: crash
  replicas: 3
  template:
    metadata:
      labels:
        app: crash
    spec:
      containers:
      - name: crash
        image: wjsc/crash:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"