apiVersion: apps/v1
kind: Deployment
metadata:
  name: work-deployment
  namespace: resilience
spec:
  selector:
    matchLabels:
      app: work
  replicas: 3
  template:
    metadata:
      labels:
        app: work
    spec:
      containers:
      - name: work
        image: wjsc/work:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"